version: "3.8"
services:
  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3001:80"
    restart: always

  backend:
    build: ./server
    container_name: backend
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ./server/.env
    volumes:
      # Mount the service account into /app inside the container (read-only)
      - ./server/firebase-service-account.json:/app/firebase-service-account.json:ro
    depends_on:
      - frontend
