version: '3'
services:
  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3001:80"
    restart: always

  backend:
    build: ./server
    container_name: backend
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ./server/.env
    depends_on:
      - frontend
